from backend.core.repositories.user_repository import UserRepository
from backend.core.repositories.vacancy_repository import VacancyRepository
from backend.core.repositories.tag_repository import TagRepository
from backend.core.repositories.company_repository import CompanyRepository
from backend.core.repositories.application_repository import ApplicationRepository