export const enum ERouteNames {
  DEFAULT_ROUTE = "/",
  EMPTY_ROUTE = "",
  DASHBOARD_ROUTE = "dashboard-applicant",
  INTERVIEWS_ROUTE = "interviews",
  DASHBOARD_ADMIN_ROUTE = "dashboard-admin",
  DASHBOARD_COMPANY_ROUTE = "dashboard-company",
  COMPANY_INTERNSHIP_ROUTE = "internship",
  COMPANY_PROFILE_ROUTE = "profile",
  DASHBOARD_UNIVERSITY_ROUTE = "dashboard-university",
  VACANCY_ROUTE = "vacancy/:vacancyId",
  VACANCY_DETAIL_ROUTE = "vacancy",
  STATISTICS_ROUTE = "statistics",
  AUTH_ROUTE = "auth",
  LOGIN_ROUTE = "login",
  REGISTER_ROUTE = "register",
  PROFILE_ROUTE = "profile",
  MANAGEMENT_ROUTE = "management",
  VACANCY_MANAGEMENT_ROUTE = "vacancy-management/:vacancyId",
  STUDENT_ROUTE = "student/:studentId",
  UNIVERSITY_INTERNSHIP_ROUTE = "university-internship",
  RESIDENTS_RATING_ROUTE = "residents-rating",
  COMPANY_DETAIL_ROUTE = "company/:companyId",
}
